[package]
name = "rhexdump"
version = "0.1.0"
authors = ["S1lverTongue <tmay2013@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
